### ISSUE TITLE
[Bug]: Cart Note — Note not present within Shopify Order

### ISSUE THREAD

**Issue by avcohen** [getnacelle/nacelle-js#319]
### Project

packages/shopify-cart

### Project Version

^1.0.0-beta.0

### Is this a new issue?

Yes - I've checked the existing Issues, and I'm reporting a new issue.

### What was the expected behavior?

I'm getting successful network requests and a valid response from Nacelle showing that a value for `note` has in fact been added to the cart.

Upon checkout, the note is not present within the order on Shopify — I would expect the note to be present.

### What happened?

```
{
    "id": "gid://shopify/Cart/XXXXXXXXX",
     ...(truncated for legibility)
    "note": "Gift_Message: Test cart note",
    "attributes": [],
    "discountCodes": []
}
```

### Link to Reproduction

Cannot provide

### Node.js Version

v16.13.0

### Operating System

MacOS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NWRichmond** [comment]
Hi @avcohen! `@nacelle/shopify-cart` only controls the Shopify cart _data_, and the `cart.note` data is being set as expected. For example: https://codesandbox.io/s/nacelle-shopify-cart-demonstrate-cart-note-update-swrqt6?file=/src/App.tsx:1685-2260

https://user-images.githubusercontent.com/5732000/214381608-ea5aadbd-f646-48de-9fbd-5e0ab89f3390.mov

This shows that `cart.note` is indeed being set as expected whether defining a note in `cartClient.cartCreate` or `cartClient.cartNoteUpdate`.

The CodeSandbox linked above uses `@nacelle/shopify-cart@1.0.0-beta.0` because that's the version specified in this issue. But please note that `@nacelle/shopify-cart@1.x` is stable now, so we recommend updating to the latest version:

```
npm i @nacelle/shopify-cart@latest
```

If you need assistance with the presentation layer of Shopify checkouts, I'd recommend asking a Shopify expert or Shopify support.

**Comment by avcohen** [comment]
Thanks for the prompt reply.

Can you clarify when you say "`@nacelle/shopify-cart` only controls the Shopify cart data"?

I would assume whatever value is being set on the `note` field via Nacelle should be relayed to Shopify upon checkout, no?

**Comment by NWRichmond** [comment]
Sure thing, @avcohen, I'm happy to clarify.

> `@nacelle/shopify-cart` only controls the Shopify cart data

This package is only concerned with creating & modifying Shopify [Carts](https://shopify.dev/api/storefront/2023-01/objects/Cart). When a `cart.note` is applied via `@nacelle/shopify-cart`'s methods, the effect is the same as if you were to use the Shopify Storefront API to add a `note` to a Shopify Cart.

Let's say that you use `@nacelle/shopify-cart` to create a Shopify Cart and apply a `note` to it. If you query the Shopify Storefront API (with the [`cart` query](https://shopify.dev/api/storefront/2023-01/queries/cart)) using the `id` of the cart you created with `@nacelle/shopify-cart`, you will see that the Shopify Storefront API returns a `cart` object with the expected `note`.

What happens with that `note` (for example, in the context of a Shopify Checkout) in Shopify's system is outside of the control of [Nacelle](https://nacelle.com) or `@nacelle/shopify-cart`.

> I would assume whatever value is being set on the note field via Nacelle should be relayed to Shopify upon checkout, no?

Although this is not a concern of `@nacelle/shopify-cart`, I completed a test checkout and the `note` was conveyed to the Shopify checkout in Shopify Admin:

![shopify_admin_checkout_with_note](https://user-images.githubusercontent.com/5732000/214426867-ebc9b618-815e-437f-8b14-373fea4a3f35.png)

If your goal is to make the `cart.note` visible on the checkout page itself (rather than the Order page in Shopify Admin), I suggest that you consult with a Shopify expert or Shopify support to see what's needed to accomplish this.
